# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b2048aa97e2d6e4e2549c4a6cf7495379e531b6fa45db4634d0483373cea9fecf3fc547b6db6720773fa47435be8bb4b532e35a8525c703f5eb7d245f4f0027

test:
  secret_key_base: f6769e752f1083bab41710b4e9b0ac52e6073891e860a865b8d606cc03666c722e58e161b84b0c2b920d2d02fa0a7eb65cb11a82079184246836e9fea6ea0425

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
